apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: multi-app
spec:
  project: default
  source:
    repoURL: https://github.com/OutOfContext/ArgoCD-demo.git
    targetRevision: HEAD
    path: base/nginx-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: multi-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true