apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multi-app
resources:
  - ../../base/guestbook
  - ../../base/nginx-demo
commonLabels:
  environment: dev
  managed-by: argocd